### ISSUE TITLE
DataCollector podAnnotations does not work

### ISSUE THREAD

**Issue by modularTaco** [undefinedhashtag/charts#2]
Die Pod Annotations für Data Collector werden nicht gesetzt.
Eine mögliche Ursache könnte sein, dass das annotations Feld falsch eingerückt ist:
```
  template:
    metadata:
      labels:
        app: {{ template "datacollector.name" . }}
        release: {{ .Release.Name }}
        {{- if .Values.podAnnotations }}
        annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
        {{- end }}
    spec:
```
(`annotations` ist unterhalb von `labels`)

z.B. bei https://github.com/undefinedhashtag/charts/blob/master/charts/cert-manager/templates/deployment.yaml sieht man, dass `annotations` aber auf der selben Ebene wie `labels` stehen muss.
